# Generated by Django 5.1.3 on 2024-12-02 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=255)),
                ('building_address', models.CharField(max_length=255)),
                ('building_city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_initial', models.CharField(blank=True, default='', max_length=1, null=True)),
                ('customer_birthdate', models.DateField(blank=True, default=None, null=True)),
                ('customer_location', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('assigned_building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StateSpacesHub.building')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='StateSpacesHub.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=255)),
                ('venue_type', models.CharField(default='None', max_length=255, null=True)),
                ('venue_floor', models.CharField(max_length=50)),
                ('venue_address', models.CharField(max_length=255)),
                ('venue_city', models.CharField(max_length=255)),
                ('venue_floor_area', models.PositiveIntegerField()),
                ('venue_capacity', models.PositiveIntegerField()),
                ('venue_status', models.CharField(choices=[('A', 'Available'), ('R', 'Reserved'), ('U', 'Under Renovation')], default='A', max_length=1)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='StateSpacesHub.building')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('number_of_participants', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='StateSpacesHub.customer')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='StateSpacesHub.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Renovation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovations', to='StateSpacesHub.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_type', models.CharField(max_length=255)),
                ('amenity_description', models.TextField()),
                ('amenity_quantity', models.PositiveIntegerField(default=1)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='StateSpacesHub.venue')),
            ],
        ),
    ]
