# Generated by Django 5.1.3 on 2024-11-27 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=255)),
                ('venue_type', models.CharField(blank=True, max_length=255, null=True)),
                ('venue_floor', models.CharField(max_length=50)),
                ('venue_address', models.CharField(max_length=255)),
                ('venue_city', models.CharField(max_length=255)),
                ('venue_floor_area', models.PositiveIntegerField()),
                ('venue_capacity', models.PositiveIntegerField()),
                ('venue_status', models.BooleanField(default=False)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='StateSpacesHub.building')),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_type', models.CharField(max_length=255)),
                ('amenity_description', models.TextField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='StateSpacesHub.venue')),
            ],
        ),
    ]
