# Generated by Django 5.1.3 on 2024-11-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StateSpacesHub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='venue_status',
            field=models.CharField(choices=[('A', 'Available'), ('R', 'Reserved'), ('U', 'Under Renovation')], default='A', max_length=1),
        ),
    ]
